export const db = {
    productos: [
        {
            id: 1,
            descripcion: 'Lapicera Azul',
            proveedor: 'Pelikan',
            precioUnitarioCompra: 1.2,
            precioUnitarioVenta: 2,
            cantidadPorCaja: 50,
            stockActual: 55,
        },
        {
            id: 2,
            descripcion: 'Lapicera Negra',
            proveedor: 'Pelikan',
            precioUnitarioCompra: 1.2,
            precioUnitarioVenta: 2,
            cantidadPorCaja: 50,
            stockActual: 110,
        },
        {
            id: 3,
            descripcion: 'Lapiz hb',
            proveedor: 'Pelikan',
            precioUnitarioCompra: 0.7,
            precioUnitarioVenta: 1.5,
            cantidadPorCaja: 50,
            stockActual: 75,
        },
        {
            id: 4,
            descripcion: 'Goma',
            proveedor: 'Pelikan',
            precioUnitarioCompra: 0.5,
            precioUnitarioVenta: 0.9,
            cantidadPorCaja: 40,
            stockActual: 130,
        },
        {
            id: 5,
            descripcion: 'Regla',
            proveedor: 'Pizzini',
            precioUnitarioCompra: 1.5,
            precioUnitarioVenta: 2.3,
            cantidadPorCaja: 20,
            stockActual: 105,
        },
        {
            id: 6,
            descripcion: 'Transportador',
            proveedor: 'Pizzini',
            precioUnitarioCompra: 1.5,
            precioUnitarioVenta: 2.3,
            cantidadPorCaja: 20,
            stockActual: 100,
        },
        {
            id: 7,
            descripcion: 'Marcador permanente rojo',
            proveedor: 'Sharpie',
            precioUnitarioCompra: 2.5,
            precioUnitarioVenta: 4,
            cantidadPorCaja: 10,
            stockActual: 110,
        },
        {
            id: 8,
            descripcion: 'Marcador permanente azul',
            proveedor: 'Sharpie',
            precioUnitarioCompra: 2.4,
            precioUnitarioVenta: 3.9,
            cantidadPorCaja: 10,
            stockActual: 110,
        },
        {
            id: 9,
            descripcion: 'Marcador permanente negro',
            proveedor: 'Sharpie',
            precioUnitarioCompra: 2.2,
            precioUnitarioVenta: 3.8,
            cantidadPorCaja: 10,
            stockActual: 100,
        },
        {
            id: 10,
            descripcion: 'Cartulina verde',
            proveedor: 'Papelart',
            precioUnitarioCompra: 1,
            precioUnitarioVenta: 1.8,
            cantidadPorCaja: 10,
            stockActual: 80,
        },
        {
            id: 11,
            descripcion: 'Cartulina amarilla',
            proveedor: 'Papelart',
            precioUnitarioCompra: 1.2,
            precioUnitarioVenta: 2,
            cantidadPorCaja: 10,
            stockActual: 80,
        },
        {
            id: 12,
            descripcion: 'Pack Lapices de Colores',
            proveedor: 'Faber Castell',
            precioUnitarioCompra: 5,
            precioUnitarioVenta: 9,
            cantidadPorCaja: 20,
            stockActual: 210,
        },
        {
            id: 13,
            descripcion: 'Mapa Arg Político',
            proveedor: 'Map',
            precioUnitarioCompra: 0.4,
            precioUnitarioVenta: 1.2,
            cantidadPorCaja: 50,
            stockActual: 60,
        },
        {
            id: 14,
            descripcion: 'Mapa Arg Relieve',
            proveedor: 'Map',
            precioUnitarioCompra: 0.4,
            precioUnitarioVenta: 1.1,
            cantidadPorCaja: 40,
            stockActual: 60,
        },
        {
            id: 15,
            descripcion: 'Sacapuntas',
            proveedor: 'Pizzini',
            precioUnitarioCompra: 0.5,
            precioUnitarioVenta: 1.2,
            cantidadPorCaja: 30,
            stockActual: 110,
        },
        {
            id: 16,
            descripcion: 'Cuaderno Cuadriculado',
            proveedor: 'Gloria',
            precioUnitarioCompra: 2.5,
            precioUnitarioVenta: 4.8,
            cantidadPorCaja: 10,
            stockActual: 60,
        },
        {
            id: 17,
            descripcion: 'Cuaderno Rayado',
            proveedor: 'Gloria',
            precioUnitarioCompra: 2.5,
            precioUnitarioVenta: 4.8,
            cantidadPorCaja: 10,
            stockActual: 60,
        },
        {
            id: 18,
            descripcion: 'Resma A4',
            proveedor: 'Ledesma',
            precioUnitarioCompra: 4,
            precioUnitarioVenta: 10,
            cantidadPorCaja: 5,
            stockActual: 100,
        },
        {
            id: 19,
            descripcion: 'Hojas x100 Rayadas',
            proveedor: 'Rivadavia',
            precioUnitarioCompra: 3,
            precioUnitarioVenta: 5.8,
            cantidadPorCaja: 20,
            stockActual: 120,
        },
        {
            id: 20,
            descripcion: 'Hojas x100 Cuadriculadas',
            proveedor: 'Rivadavia',
            precioUnitarioCompra: 3,
            precioUnitarioVenta: 5.7,
            cantidadPorCaja: 20,
            stockActual: 120,
        },
    ],
    proveedores: [
        {
            id: 1,
            nombre: 'Pelikan',
            email: 'pelikan@pelikan.com',
            direccion: 'Av. Rivadavia 2651',
            telefono: '4966-8365',
        },
        {
            id: 2,
            nombre: 'Rivadavia',
            email: 'contacto@rivadavia.com',
            direccion: 'Av. Alberdi 4618',
            telefono: '5156-8122',
        },
    ],
    ventasDeHoy: [],
    usuarios: [
        {
            id: 1,
            nombreUsuario: 'admin',
            nombre: 'Oscar',
            apellido: 'Rodriguez',
            fechaCreacion: 1734678272367,
            role: 'admin',
            password: 'hJ.56lK.g',
        },
        {
            id: 2,
            nombreUsuario: 'josegarcia',
            nombre: 'José',
            apellido: 'García',
            fechaCreacion: 1734678272767,
            role: 'manager',
            password: '15afG1.cv',
        },
        {
            id: 2,
            nombreUsuario: 'carlosperez',
            nombre: 'Carlos',
            apellido: 'Perez',
            fechaCreacion: 1734678273267,
            role: 'user',
            password: 'ta68fgVV1.',
        },
    ],
    pedidosAProveedores: [
        {
            id: 1,
            fechaPedido: '07/01/2025',
            horaPedido: '15:04',
            importeTotal: 60,
            detallesPedido: [
                {
                    id: 1,
                    cantidadAPedir: 1,
                    descripcion: 'Lapicera Azul',
                    proveedor: 'Pelikan',
                    importe: 60,
                },
            ],
        },
    ],
    historialVentas: [
        {
            '08/01/2025': [
                {
                    id: '1736496830937',
                    detalles: [
                        {
                            id: 11,
                            cantidad: 3,
                            descripcion: 'Cartulina amarilla',
                            precioUnitarioCompra: 1.2,
                            precioUnitarioVenta: 2,
                            importe: 6,
                        },
                        {
                            id: 10,
                            cantidad: 2,
                            descripcion: 'Cartulina verde',
                            precioUnitarioCompra: 1,
                            precioUnitarioVenta: 1.8,
                            importe: 3.6,
                        },
                    ],
                    fecha: '10/01/2025',
                    hora: '05:13',
                    importe: 9.6,
                    metodoDePago: 'Efectivo',
                },
                {
                    id: '1736496862619',
                    detalles: [
                        {
                            id: 4,
                            cantidad: 1,
                            descripcion: 'Goma',
                            precioUnitarioCompra: 0.5,
                            precioUnitarioVenta: 0.9,
                            importe: 0.9,
                        },
                        {
                            id: 3,
                            cantidad: 1,
                            descripcion: 'Lapiz hb',
                            precioUnitarioCompra: 0.7,
                            precioUnitarioVenta: 1.5,
                            importe: 1.5,
                        },
                        {
                            id: 5,
                            cantidad: 1,
                            descripcion: 'Regla',
                            precioUnitarioCompra: 1.5,
                            precioUnitarioVenta: 2.3,
                            importe: 2.3,
                        },
                        {
                            id: 15,
                            cantidad: 1,
                            descripcion: 'Sacapuntas',
                            precioUnitarioCompra: 0.5,
                            precioUnitarioVenta: 1.2,
                            importe: 1.2,
                        },
                    ],
                    fecha: '10/01/2025',
                    hora: '05:14',
                    importe: 5.9,
                    metodoDePago: 'QR',
                },
                {
                    id: '1736496883281',
                    detalles: [
                        {
                            id: 13,
                            cantidad: 2,
                            descripcion: 'Mapa Arg Político',
                            precioUnitarioCompra: 0.4,
                            precioUnitarioVenta: 1.2,
                            importe: 2.4,
                        },
                        {
                            id: 14,
                            cantidad: 2,
                            descripcion: 'Mapa Arg Relieve',
                            precioUnitarioCompra: 0.4,
                            precioUnitarioVenta: 1.1,
                            importe: 2.2,
                        },
                    ],
                    fecha: '10/01/2025',
                    hora: '05:14',
                    importe: 4.6,
                    metodoDePago: 'Visa Débito',
                },
                {
                    id: '1736496895898',
                    detalles: [
                        {
                            id: 18,
                            cantidad: 4,
                            descripcion: 'Resma A4',
                            precioUnitarioCompra: 4,
                            precioUnitarioVenta: 10,
                            importe: 40,
                        },
                    ],
                    fecha: '10/01/2025',
                    hora: '05:14',
                    importe: 40,
                    metodoDePago: 'Visa Débito',
                },
                {
                    id: '1736496906488',
                    detalles: [
                        {
                            id: 12,
                            cantidad: 1,
                            descripcion: 'Pack Lapices de Colores',
                            precioUnitarioCompra: 5,
                            precioUnitarioVenta: 9,
                            importe: 9,
                        },
                    ],
                    fecha: '10/01/2025',
                    hora: '05:15',
                    importe: 9,
                    metodoDePago: 'Efectivo',
                },
                {
                    id: '1736496933083',
                    detalles: [
                        {
                            id: 8,
                            cantidad: 5,
                            descripcion: 'Marcador permanente azul',
                            precioUnitarioCompra: 2.4,
                            precioUnitarioVenta: 3.9,
                            importe: 19.5,
                        },
                        {
                            id: 9,
                            cantidad: 5,
                            descripcion: 'Marcador permanente negro',
                            precioUnitarioCompra: 2.2,
                            precioUnitarioVenta: 3.8,
                            importe: 19,
                        },
                        {
                            id: 7,
                            cantidad: 5,
                            descripcion: 'Marcador permanente rojo',
                            precioUnitarioCompra: 2.5,
                            precioUnitarioVenta: 4,
                            importe: 20,
                        },
                    ],
                    fecha: '10/01/2025',
                    hora: '05:15',
                    importe: 58.5,
                    metodoDePago: 'QR',
                },
                {
                    id: '1736496955741',
                    detalles: [
                        {
                            id: 2,
                            cantidad: 2,
                            descripcion: 'Lapicera Negra',
                            precioUnitarioCompra: 1.2,
                            precioUnitarioVenta: 2,
                            importe: 4,
                        },
                        {
                            id: 1,
                            cantidad: 10,
                            descripcion: 'Lapicera Azul',
                            precioUnitarioCompra: 1.2,
                            precioUnitarioVenta: 2,
                            importe: 20,
                        },
                    ],
                    fecha: '10/01/2025',
                    hora: '05:15',
                    importe: 24,
                    metodoDePago: 'Efectivo',
                },
            ],
            '10/01/2025': [
                {
                    id: '1736496830937',
                    detalles: [
                        {
                            id: 11,
                            cantidad: 3,
                            descripcion: 'Cartulina amarilla',
                            precioUnitarioCompra: 1.2,
                            precioUnitarioVenta: 2,
                            importe: 6,
                        },
                        {
                            id: 10,
                            cantidad: 2,
                            descripcion: 'Cartulina verde',
                            precioUnitarioCompra: 1,
                            precioUnitarioVenta: 1.8,
                            importe: 3.6,
                        },
                    ],
                    fecha: '10/01/2025',
                    hora: '05:13',
                    importe: 9.6,
                    metodoDePago: 'Efectivo',
                },
                {
                    id: '1736496862619',
                    detalles: [
                        {
                            id: 4,
                            cantidad: 1,
                            descripcion: 'Goma',
                            precioUnitarioCompra: 0.5,
                            precioUnitarioVenta: 0.9,
                            importe: 0.9,
                        },
                        {
                            id: 3,
                            cantidad: 1,
                            descripcion: 'Lapiz hb',
                            precioUnitarioCompra: 0.7,
                            precioUnitarioVenta: 1.5,
                            importe: 1.5,
                        },
                        {
                            id: 5,
                            cantidad: 1,
                            descripcion: 'Regla',
                            precioUnitarioCompra: 1.5,
                            precioUnitarioVenta: 2.3,
                            importe: 2.3,
                        },
                        {
                            id: 15,
                            cantidad: 1,
                            descripcion: 'Sacapuntas',
                            precioUnitarioCompra: 0.5,
                            precioUnitarioVenta: 1.2,
                            importe: 1.2,
                        },
                    ],
                    fecha: '10/01/2025',
                    hora: '05:14',
                    importe: 5.9,
                    metodoDePago: 'QR',
                },
                {
                    id: '1736496883281',
                    detalles: [
                        {
                            id: 13,
                            cantidad: 2,
                            descripcion: 'Mapa Arg Político',
                            precioUnitarioCompra: 0.4,
                            precioUnitarioVenta: 1.2,
                            importe: 2.4,
                        },
                        {
                            id: 14,
                            cantidad: 2,
                            descripcion: 'Mapa Arg Relieve',
                            precioUnitarioCompra: 0.4,
                            precioUnitarioVenta: 1.1,
                            importe: 2.2,
                        },
                    ],
                    fecha: '10/01/2025',
                    hora: '05:14',
                    importe: 4.6,
                    metodoDePago: 'Visa Débito',
                },
                {
                    id: '1736496895898',
                    detalles: [
                        {
                            id: 18,
                            cantidad: 4,
                            descripcion: 'Resma A4',
                            precioUnitarioCompra: 4,
                            precioUnitarioVenta: 10,
                            importe: 40,
                        },
                    ],
                    fecha: '10/01/2025',
                    hora: '05:14',
                    importe: 40,
                    metodoDePago: 'Visa Débito',
                },
                {
                    id: '1736496906488',
                    detalles: [
                        {
                            id: 12,
                            cantidad: 1,
                            descripcion: 'Pack Lapices de Colores',
                            precioUnitarioCompra: 5,
                            precioUnitarioVenta: 9,
                            importe: 9,
                        },
                    ],
                    fecha: '10/01/2025',
                    hora: '05:15',
                    importe: 9,
                    metodoDePago: 'Efectivo',
                },
                {
                    id: '1736496933083',
                    detalles: [
                        {
                            id: 8,
                            cantidad: 5,
                            descripcion: 'Marcador permanente azul',
                            precioUnitarioCompra: 2.4,
                            precioUnitarioVenta: 3.9,
                            importe: 19.5,
                        },
                        {
                            id: 9,
                            cantidad: 5,
                            descripcion: 'Marcador permanente negro',
                            precioUnitarioCompra: 2.2,
                            precioUnitarioVenta: 3.8,
                            importe: 19,
                        },
                        {
                            id: 7,
                            cantidad: 5,
                            descripcion: 'Marcador permanente rojo',
                            precioUnitarioCompra: 2.5,
                            precioUnitarioVenta: 4,
                            importe: 20,
                        },
                    ],
                    fecha: '10/01/2025',
                    hora: '05:15',
                    importe: 58.5,
                    metodoDePago: 'QR',
                },
                {
                    id: '1736496955741',
                    detalles: [
                        {
                            id: 2,
                            cantidad: 2,
                            descripcion: 'Lapicera Negra',
                            precioUnitarioCompra: 1.2,
                            precioUnitarioVenta: 2,
                            importe: 4,
                        },
                        {
                            id: 1,
                            cantidad: 10,
                            descripcion: 'Lapicera Azul',
                            precioUnitarioCompra: 1.2,
                            precioUnitarioVenta: 2,
                            importe: 20,
                        },
                    ],
                    fecha: '10/01/2025',
                    hora: '05:15',
                    importe: 24,
                    metodoDePago: 'Efectivo',
                },
            ],
        },
    ],
}
