export const db = {
    productos: [
        {
            id: 1,
            nombre: 'Lapicera',
            color: 'azul',
            proveedor: 'Pelikan',
            precioUnitario: 1.2,
            cantidadPorCaja: 50,
        },
        {
            id: 2,
            nombre: 'Lapicera',
            color: 'negro',
            proveedor: 'Pelikan',
            precioUnitario: 1.2,
            cantidadPorCaja: 50,
        },
        {
            id: 3,
            nombre: 'Lapiz hb',
            color: 'negro',
            proveedor: 'Pelikan',
            precioUnitario: 0.7,
            cantidadPorCaja: 50,
        },
        {
            id: 4,
            nombre: 'Goma',
            color: 'blanca',
            proveedor: 'Pelikan',
            precioUnitario: 0.5,
            cantidadPorCaja: 40,
        },
        {
            id: 5,
            nombre: 'Regla',
            color: 'n/a',
            proveedor: 'Pizzini',
            precioUnitario: 1.5,
            cantidadPorCaja: 20,
        },
        {
            id: 6,
            nombre: 'Transportador',
            color: 'n/a',
            proveedor: 'Pizzini',
            precioUnitario: 1.5,
            cantidadPorCaja: 20,
        },
        {
            id: 7,
            nombre: 'Marcador permanente',
            color: 'rojo',
            proveedor: 'Sharpie',
            precioUnitario: 2.5,
            cantidadPorCaja: 10,
        },
        {
            id: 8,
            nombre: 'Marcador permanente',
            color: 'negro',
            proveedor: 'Sharpie',
            precioUnitario: 2.4,
            cantidadPorCaja: 10,
        },
        {
            id: 9,
            nombre: 'Marcador permanente',
            color: 'azul',
            proveedor: 'Sharpie',
            precioUnitario: 2.2,
            cantidadPorCaja: 10,
        },
        {
            id: 10,
            nombre: 'Cartulina',
            color: 'blanca',
            proveedor: 'Papelart',
            precioUnitario: 1,
            cantidadPorCaja: 10,
        },
        {
            id: 11,
            nombre: 'Cartulina',
            color: 'varios',
            proveedor: 'Papelart',
            precioUnitario: 1.2,
            cantidadPorCaja: 10,
        },
        {
            id: 12,
            nombre: 'Lapices de Colores',
            color: 'varios',
            proveedor: 'Faber Castell',
            precioUnitario: 0.9,
            cantidadPorCaja: 40,
        },
        {
            id: 13,
            nombre: 'Mapa Arg Político',
            color: 'n/a',
            proveedor: 'Map',
            precioUnitario: 0.4,
            cantidadPorCaja: 50,
        },
        {
            id: 14,
            nombre: 'Mapa Arg Relieve',
            color: 'n/a',
            proveedor: 'Map',
            precioUnitario: 0.4,
            cantidadPorCaja: 40,
        },
        {
            id: 15,
            nombre: 'Sacapuntas',
            color: 'n/a',
            proveedor: 'Pizzini',
            precioUnitario: 0.5,
            cantidadPorCaja: 30,
        },
        {
            id: 16,
            nombre: 'Cuaderno Cuadriculado',
            color: 'n/a',
            proveedor: 'Gloria',
            precioUnitario: 2.5,
            cantidadPorCaja: 10,
        },
        {
            id: 17,
            nombre: 'Cuaderno Rayado',
            color: 'n/a',
            proveedor: 'Gloria',
            precioUnitario: 2.5,
            cantidadPorCaja: 10,
        },
        {
            id: 18,
            nombre: 'Resma A4',
            color: 'n/a',
            proveedor: 'Ledesma',
            precioUnitario: 4,
            cantidadPorCaja: 5,
        },
        {
            id: 19,
            nombre: 'Hojas x100 Rayadas',
            color: 'n/a',
            proveedor: 'Rivadavia',
            precioUnitario: 3,
            cantidadPorCaja: 20,
        },
        {
            id: 20,
            nombre: 'Hojas x100 Cuadriculadas',
            color: 'n/a',
            proveedor: 'Rivadavia',
            precioUnitario: 3,
            cantidadPorCaja: 20,
        },
    ],
    proveedores: [
        {
            id: 1,
            nombre: 'Pelikan',
            email: 'pelikan@pelikan.com',
            direccion: 'Av. Rivadavia 2651',
            telefono: '4966-8365',
        },
        {
            id: 2,
            nombre: 'Rivadavia',
            email: 'contacto@rivadavia.com',
            direccion: 'Av. Alberdi 4618',
            telefono: '5156-8122',
        },
    ],
    ventas: [
        {
            detalles: [
                {
                    id: 16,
                    cantidad: 1,
                    nombre: 'Cuaderno Cuadriculado',
                    precioUnitario: 2.5,
                    importe: 2.5,
                },
                {
                    id: 17,
                    cantidad: 2,
                    nombre: 'Cuaderno Rayado',
                    precioUnitario: 2.5,
                    importe: 5,
                },
                {
                    id: 1,
                    cantidad: 5,
                    nombre: 'Lapicera',
                    precioUnitario: 1.2,
                    importe: 6,
                },
            ],
            fecha: '19/12/2024',
            hora: '13:55',
            id: 1734677742863,
            importe: 13.5,
            metodoDePago: 'Efectivo',
        },
        {
            detalles: [
                {
                    id: 4,
                    cantidad: 1,
                    nombre: 'Goma',
                    precioUnitario: 0.5,
                    importe: 0.5,
                },
                {
                    id: 3,
                    cantidad: 2,
                    nombre: 'Lapiz hb',
                    precioUnitario: 0.7,
                    importe: 1.4,
                },
                {
                    id: 15,
                    cantidad: 1,
                    nombre: 'Sacapuntas',
                    precioUnitario: 0.5,
                    importe: 0.5,
                },
            ],
            fecha: '18/12/2024',
            hora: '16:04',
            id: 1734678272266,
            importe: 2.4,
            metodoDePago: 'QR',
        },
        {
            detalles: [
                {
                    id: 4,
                    cantidad: 3,
                    nombre: 'Goma',
                    precioUnitario: 0.5,
                    importe: 1.5,
                },
                {
                    id: 15,
                    cantidad: 6,
                    nombre: 'Sacapuntas',
                    precioUnitario: 0.5,
                    importe: 3,
                },
            ],
            fecha: '20/12/2024',
            hora: '13:16',
            id: 1734678272267,
            importe: 4.5,
            metodoDePago: 'Maestro',
        },
    ],
}
